### ISSUE TITLE
12:00 AM and 12:00 PM are both considered 00:00 

### ISSUE THREAD

**Issue by tedgkassen** [tjohnn/vuejs-datetimepicker#1]
The time passed into the update function says it's 00:00:00 when I select both 12 AM and 12 PM

**Comment by tedgkassen** [comment]
Think I found it: https://github.com/tjohnn/vuejs-datetimepicker/pull/2

**Comment by tjohnn** [comment]
Bug fixed, thanks to @tedgkassen
