### ISSUE TITLE
Changing from AM to PM resets date to "2000-01-01 12:00:00"

### ISSUE THREAD

**Issue by kodi** [tjohnn/vuejs-datetimepicker#13]
https://streamable.com/7l94r

**Comment by kodi** [comment]
Sorry, my bad, used `h:i:s` instead of `H:i:s`

still, strange bug, might need better validation or fixing.

**Comment by tjohnn** [comment]
@kodi please confirm that the bug is fixed now

**Comment by kodi** [comment]
Hey @tjohnn, I don't know what changed, but when I installed 1.1.6, calendar was no longer working.

I was using it like this `<datetime format="YYYY-MM-DD H:i:s" width="250" v-model="dateStart"></datetime>`

where dateStart is custom getter using `vue-class-component` and `vuex-class`

```js
  get dateStart()  {
    return format(new Date(this.activePoly.dateStart * 1000), this.format);
  }
```

installing 1.1.6 makes date field show `1970-01-01 1.1...` date, while downgrading to 1.1.5 makes everything work as expected.

**Comment by tjohnn** [comment]
In which hook is your dateStart() methods?

**Comment by kodi** [comment]
I tried that, works on 1.1.5, while when I switch to 1.1.6, I get `1970-01-01 01:00:00` no matter what i try.

**Comment by kodi** [comment]
I wonder why you removed watch, everything worked as expected.

It was my fault in a first place for making wrong format:

> Sorry, my bad, used `h:i:s` instead of `H:i:s`

**Comment by tjohnn** [comment]
@kodi Please check if every bug is fixed now
