### ISSUE TITLE
doesn't work when other Dateformat

### ISSUE THREAD

**Issue by 08-15at** [tjohnn/vuejs-datetimepicker#14]
example:
    <datetime format="MM/DD/YYYY" width="300px" v-model="val"></datetime>
does work

    <datetime format="DD/MM/YYYY" width="300px" v-model="val"></datetime>

does not
thx

**Comment by tjohnn** [comment]
@08-15at Could you please explain what does not work properly?

**Comment by 08-15at** [comment]
uhh, sorry,
there was a line missing:
standard Date format 
          <datetime style="z-index:100" format="MM-DD-YYYY H:i:s"  v-model="val"></datetime>
works,
as soon as I try to reorder day and month to european style format the complete Browser Tab freezes. 
          <datetime style="z-index:100" format="DD-MM-YYYY H:i:s"  v-model="val"></datetime>
Have to close and reopen the tab.
to be sure, I'm not passing wrong values in val I set this to 
val: "05-05-2018 00:00:00"
I'm using date-fns functions in my code, too installed version is date-fns@1.29.0 

thx for your help

**Comment by tjohnn** [comment]
@08-15at Please confirm if the issues is fixed now.

**Comment by 08-15at** [comment]
works perfectly now, thank you very much for your fast fix.
