### ISSUE TITLE
Module build failed: Error: Couldn't find preset "es2016" relative to directory "

### ISSUE THREAD

**Issue by Lak0sta** [tjohnn/vuejs-datetimepicker#16]
in ./~/vuejs-datetimepicker/src/datetime_picker.vue

Module build failed: Error: Couldn't find preset "es2016" relative to directory "
node_modules\\vuejs-datetimepicker"
    at node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (node_modules\babel-loader\lib\index.js:49:20)
    at Object.module.exports node_modules\babel-loader\lib\index.js:174:20)

 @ ./~/vuejs-datetimepicker/src/datetime_picker.vue 8:2-99
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/Events/EditEventPage/index.vue
 @ ./src/components/pages/Events/EditEventPage/index.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./builds/dev-client ./src/main.js

**Comment by steven87vt** [comment]
I ran in the same issue, im using preset-env and stage-2/3 in .bablerc. Is there a way to work around this without having to bring the 2016 package into my dev dependencies?

**Comment by tjohnn** [comment]
@Lak0sta @steven87vt Can you give info on how I can regenerate the error?

**Comment by steven87vt** [comment]
.bablerc:

    {
        "presets": [
            [
                "env",
                {
                    "targets": {
                        "firefox": "61.0.1"
                    }
                }
            ]
        ],
        "plugins": [
            "transform-runtime",
            "transform-async-to-generator",
            //stage 2 plugins must be declared manually because preset-env does not include them by default and will not accept stage-2 as an option.
            "syntax-dynamic-import",
            "transform-class-properties",
            "transform-decorators",
            //stage 3 plugins must be declared manually because preset-env does not include them by default and will not accept stage-2 as an option.
            "transform-object-rest-spread",
            "transform-async-generator-functions",
            "syntax-trailing-function-commas", //trailing-commas, async, exponentiation will be removed in the next major since they are stage 4 already
            "transform-async-to-generator",
            "transform-exponentiation-operator"

        ],
        "comments": false
    }


package.json dev dependencies:

    "babel-loader": "^6.2.10",
    "babel-plugin-transform-async-to-generator": "^6.22.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-env": "~1.7.0",
    "babel-preset-stage-2": "~6.24.1",
    "babel-preset-stage-3": "~6.24.1",
    //"babel-preset-es2016": "~6.24.1", //uncomment this and you generate the error

Side note, i have to include your library in the include section of my webpack vue rule. I think it would be cool if you output this as a js bundled project rather then a raw vue component. This way i can only worry about my raw vue components and just import and use your stuff right away without having to include it my loader definition.

webpack.config.js

     rules: [
         {
             test: /\.vue$/,
             include: [
                 /ClientApp/,
                 path.resolve(__dirname, 'node_modules/vuejs-datetimepicker'),
             ],
             use: 'vue-loader'
         },

**Comment by trikarai** [comment]
try change 
`..\node_modules\vuejs-datetimepicker\.babelrc`

with your babel root 

`["env", { "modules": false }],
    "stage-2"`

**Comment by Lak0sta** [comment]
You can also close this issue @trikarai solution helped me
