### ISSUE TITLE
shows NaN NaN NaN NaN 

### ISSUE THREAD

**Issue by Stozen-spb** [tjohnn/vuejs-datetimepicker#17]
when sets date format to 'MM-DD-YYYY H:i:s' calendar and v-model show NaN everywhere  in Firefox.
Also be good if you add y18n to this datepicker.

**Comment by Stozen-spb** [comment]
oops, sorry try DD-MM-YYYY H:i:s in firefox

**Comment by Lak0sta** [comment]
Have the same issue with `YYYY-MM-DD H:i:s` but in safari, still didn't find a solution

**Comment by tjohnn** [comment]
Hi @Lak0sta @Stozen-spb,  please help confirm from your side that this issues are solved in the latest commit. Sorry for my late response @Stozen-spb

**Comment by Lak0sta** [comment]
@tjohnn  Now works correctly, thank you for helping!
