### ISSUE TITLE
Show only time picker

### ISSUE THREAD

**Issue by shubhwebkul** [tjohnn/vuejs-datetimepicker#24]
Is it possible to disable date picker either the date picker or time picker according to requirements .?

**Comment by tjohnn** [comment]
Yes please check out the readme for date-only and time-only formats, specifying a date-only format hides the time picker, same goes for a time-only format

**Comment by shubhwebkul** [comment]
Thanks tjohnn for a very quick response. 
Now I am getting these errors (PFA) Am I doing something wrong or what.?
![image](https://user-images.githubusercontent.com/41280839/53805951-967adf00-3f71-11e9-9ee1-63591e907c1e.png)

**Comment by tjohnn** [comment]
Hmm.. I will have to take a look at that later today.

**Comment by tjohnn** [comment]
May I know the default value of the time you are using in `v-model`?

**Comment by shubhwebkul** [comment]
when I bind it to a variable through v-model and give that variable a default value ("06:30:40"), it is converting that value of that variable to NaN:NaN:00

**Comment by tjohnn** [comment]
@shubhwebkul  checkout the latest commit

**Comment by shubhwebkul** [comment]
Thanks a lot for the latest update @tjohnn 
now this is working as expected but it's showing a warning.
![image](https://user-images.githubusercontent.com/41280839/53869554-78b78380-401e-11e9-91b1-9d1051661d9f.png)

**Comment by tjohnn** [comment]
Please post your time format and the default value you bind with v-model

**Comment by shubhwebkul** [comment]
{ "date": "2019-03-06 02:53:00", "timezone_type": 3, "timezone": "Asia/Calcutta" }
binding datetime to "date" key

**Comment by tjohnn** [comment]
What format are you using?

**Comment by shubhwebkul** [comment]
default. not providing any format

**Comment by tjohnn** [comment]
Everything should be fine now
