### ISSUE TITLE
Document listener is preventing other inputs

### ISSUE THREAD

**Issue by luchotc** [tjohnn/vuejs-datetimepicker#5]
Setting a global document listener and not propagating the event is preventing all other inputs from being completed.
Please fix!

**Comment by tjohnn** [comment]
@luchotc How do you mean by it is not allowing other inputs to complete? Could you explain better and how I can regenerate the error?

**Comment by tjohnn** [comment]
@luchotc I got the bug and I have fixed it.
Thanks.
