### ISSUE TITLE
Error: :value conflicts with v-model

### ISSUE THREAD

**Issue by Sorbing** [tjohnn/vuejs-datetimepicker#6]
Hi. I have the error `:value="value" conflicts with v-model` on import moment.
```
- :value="value" conflicts with v-model on the same element because the latter already expands to a value binding internally
@ ./node_modules/vuejs-datetimepicker/src/datetime_picker.vue 10:23-242
```

**Comment by tjohnn** [comment]
@Sorbing May I know why you would want to use `:value` and `v-model` at the same time when `v-model` can do the job that `:value` does?

**Comment by Sorbing** [comment]
@tjohnn Thanks for answer. The error appears on the require of `vuejs-datetimepicker`. I did not edit my template.

**Comment by tjohnn** [comment]
@Sorbing Please check if the issue has been fixed in the new commit
