### ISSUE TITLE
datetime component only shows current time

### ISSUE THREAD

**Issue by craigward** [tjohnn/vuejs-datetimepicker#7]
Hi, 

I'm implementing your DateTime component but for some reason, it only ever shows the current time. I've bound v-model to `<datetime>` which is pulling data from a database, but the date/time from the database never shows, only the current date/time.

Is this something I am doing wrong?

`<datetime format="YYYY-MM-DD h:i:s" width="100%" v-model="form.publish_on"></datetime>`

Vue Chrome inspector shows `form.publish_on:"2018-11-11 11:11:11"`

**Comment by tjohnn** [comment]
`v-model` generally does not work the way you are using it here, you have to use a reactive variable that is defined in your template for it, the one you are doing above should be done like this:
```
<template>
<datetime format="YYYY-MM-DD h:i:s" width="100%" v-model="date"></datetime>
</template>

<script>
import datetime from 'vuejs-datetimepicker'

export default {
  components: { datetime },
  data () {
    return {
      date: ''
    }
  },
  created ()  {
    this.date = form.publish_on
  }
}
</script>

```

**Comment by craigward** [comment]
I've changed the code to match how you have done it, but I still get the same issue. The code is really the same, form.publish_on is a reactive variable.

On the DateTime component I can see that the props being sent are:

    format: "YYYY-MM-DD h:i:s"
    name: undefined
    value: "2018-11-11 11:11:11"
    width: 100%

However, the display on the input field still only shows the current DateTime.

**Comment by tjohnn** [comment]
@craigward may I see your code implementation?

**Comment by craigward** [comment]
Sure, 

```
</template>
    <datetime format="YYYY-MM-DD h:i:s" width="100%" v-model="form.publish_on"></datetime>
</template>

<script>
  import {Form} from '../../helpers/form.js';
  import VueQuillEditor from 'vue-quill-editor';
  import datetime from 'vuejs-datetimepicker';

  Vue.use(VueQuillEditor);

  export default {
    components: {datetime},
    data() {
      return {
        form: new Form({
          title: '',
          main_body: '',
          excerpt: '',
          status: null,
          is_sticky: null,
          publish_on: null,
          meta_description: '',
          meta_title: '',
          category: null,
          author: '',
          image: '',
          image_public_id: '',
          image_format: '',
          image_version: '',
        }),
        blog_statuses: [],
        editorOption: {},
        image: '',
        tab_toggle: true,
      }
    },
    mounted() {
      axios.get('/secure/blog/'+this.$route.params.id).then(response => {
        for (let property in response.data) {
          this.form[property] = response.data[property];
        }
      });
      axios.get('/secure/blog_status/get_all').then(response => {
        this.blog_statuses = response.data;
      });
    },
    methods: {
      onSubmit() {
        this.form.put('/secure/blog/'+this.$route.params.id)
        .then(response => {
          if(response.status === 200)
          {
            this.$router.push('/blogs')
          }
        });
      },
      onFileChange(e) {
        var files = e.target.files || e.dataTransfer.files;
        if (!files.length)
          return;
        this.createImage(files[0]);
      },
      createImage(file) {
        var image = new Image();
        var reader = new FileReader();
        var vm = this;

        reader.onload = (e) => {
          vm.image = e.target.result;
          this.form.image = this.image;
        };
        reader.readAsDataURL(file);
      },
      removeImage: function (e) {
        axios.post('/secure/blog/remove_image', {
          id: this.$route.params.id,
        }).then(response => {
          this.image = '';
          this.form.image_public_id = '';
        });
      },
    }
  }
</script>
```

```
data
$route:Object
activePort:12
date:"2018-01-12 10:15:00"
day:12
days:Array[7]
hideCal:true
hour:"10"
hourIndex:0
hourSelectorVisible:false
minute:"15"
minuteIndex:0
minuteSelectorVisible:false
monthIndex:0
months:Array[12]
period:"AM"
portsHolder:Array[35]
timeStamp:"2018-01-12T10:15:00.811Z"
year:2018

props
format:"YYYY-MM-DD h:i:s"
name:undefined
value:"2018-11-11 11:11:11"
width:"100%"

computed
dateFormat:"YYYY-MM-DD h:i:s"
dateTime:"2018-1-5"
hideDate:false
hideTime:false
hours:Array[12]
minutes:Array[60]
month:"Jan"
ports:Array[35]
```

`form.publish_on:"2018-11-11 11:11:11"`

**Comment by tjohnn** [comment]
@craigward Have you tried to used `created ()` instead of `mounted ()`, I do not think the `mounted ()` hook has the access to modify reactive data of its component before render.

**Comment by craigward** [comment]
Its used on mounted as the values are being retrieved from a database. I don't have any other issues with this method anywhere else in my codebase.

I've tried a few different things, but always the same result. The DateTime component does work, I can submit values to the database without issue, it's just the display of data being retrieved. It's always the current DateTime

**Comment by tjohnn** [comment]
Okay I just realized what you want to do cannot be achieved the way you are doing it, to confirm, add a native html input tag to your template:
```
</template>
    <datetime format="YYYY-MM-DD h:i:s" width="100%" v-model="form.publish_on"></datetime>
    <input type='text' v-model="form.publish_on" />
</template>
```
 you will see that you are having the same result.
This is to confirm that it is not an issue with the datetime picker, it is the way vuejs is built generally.

**Comment by craigward** [comment]
I've just tested this, but the standard `<input>` shows the information from the database.

**Comment by craigward** [comment]
I've been looking into it a bit more via Vue inspector in Chrome. On the Datatime component: data. there is a value for `date`. Changing the value in the datepicker doesn't update it, but it looks like it should?

**Comment by tjohnn** [comment]
Okay I get the issue and fixed it, I will make a new commit in a moment, you may download that and test again. Thanks for taking time to explain the problem.

**Comment by craigward** [comment]
No worries, its a good plugin, just glad I helped :)

**Comment by tjohnn** [comment]
I have updated it, please close this trend if the issue is fixed.

**Comment by craigward** [comment]
All working now :)
